- name: Creation of the database and link to app-network
  community.docker.docker_container:
    name: mydatabase
    image: "arthurglerean/tp-devops-bdd"
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "5432:5432"