services:
    myapi:
        build:
          context: ./java
        networks:
          - app-network
        depends_on:
          - mydatabase

    mydatabase:
        build:
          context: ./bdd
        environment:
          POSTGRES_DB: ${PSQL_DB}
          POSTGRES_USER: ${PSQL_USR}
          POSTGRES_PASSWORD: ${PSQL_PWD}
        volumes:  
          - ./bdd/data:/var/lib/postgresql/data
        networks:
          - app-network

    httpd:
        build:
          context: ./httpd
        ports:
          - "80:80"
        depends_on:
          - myapi
        networks:
          - app-network

networks:
    app-network: