services:
    myapi:
        build:
          context: ./java
        networks:
          - app-network
        depends_on:
          - mydatabase
        environment:
          POSTGRES_NAME: ${POSTGRES_NAME}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - "8080:8080"

    mydatabase:
        container_name: ${POSTGRES_NAME}
        build:
          context: ./bdd
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:  
          - ./bdd/data:/var/lib/postgresql/data
        networks:
          - app-network

    httpd:
        build:
          context: ./httpd
        ports:
          - "80:80"
        depends_on:
          - myapi
        networks:
          - app-network

    front:
      build: 
        context: ./front 
      networks:
        - app-network
      ports:
        - "8084:80"

networks:
    app-network: