services:
    myapi:
        build:
          context: ./java
        networks:
          - app-network
        depends_on:
          - mydatabase
        environment:
          POSTGRES_NAME: ${POSTGRES_NAME}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ${POSTGRES_NAME}:
        build:
          context: ./bdd
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:  
          - ./bdd/data:/var/lib/postgresql/data
        networks:
          - app-network

    httpd:
        build:
          context: ./httpd
        ports:
          - "80:80"
        depends_on:
          - myapi
        networks:
          - app-network

networks:
    app-network: