- name: Creation of the front and link to app-network
  community.docker.docker_container:
    name: front
    image: "arthurglerean/tp-devops-front"
    pull: true
    networks:
      - name: "app-network"