- name: Create the Spring app container
  community.docker.docker_container:
    name: myapi
    image: "arthurglerean/tp-devops-simple-api"
    pull: true
    env_file: /home/admin/.env
    networks:
      - name: "app-network"