- name: Create the Spring app container
  community.docker.docker_container:
    name: myapi
    image: "arthurglerean/tp-devops-simple-api:latest"
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: "frontend-network"
      - name: "backend-network"