- name: Create the httpd container
  community.docker.docker_container:
    name: httpd
    image: "arthurglerean/tp-devops-httpd"
    pull: true
    networks:
      - name: "app-network"
    ports:
      - "80:80"
      - "8080:8080"