- name: Create the httpd container
  community.docker.docker_container:
    name: httpd
    image: "arthurglerean/tp-devops-httpd:latest"
    pull: yes
    networks:
      - name: "frontend-network"
    ports:
      - "80:80"
      - "8080:8080"