- name: Create the httpd container
  community.docker.docker_container:
    name: httpd
    image: arthurglerean/tp-devops-httpd
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"