- name: Create the httpd container
  community.docker.docker_container:
    name: httpd
    image: arthurglerean/tp-devops-httpd:latest
    pull: yes
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"